version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "secretpassword"
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - "5432:5432"

  core:
    image: ghcr.io/3n-company/pc-core:latest
    environment:
      DB-CONNECTION-STRING: "jdbc:postgresql://db:5432/"
      DB-USER: "postgres"
      DB-PASS: "secretpassword"
      SERVER-PORT: 8080
      PHOTO-FOLDER: "/data"
      NORMALIZATION-HOST: "normalisation"
      NORMALIZATION-THRESHOLD: 3
      COLORIZATION-HOST: "colorisation"
    ports:
      - "8080:8080"
    volumes:
      - ./photo:/data
    restart: always

  normalisation:
      image: ghcr.io/3n-company/normalisation:main

  colorisation:
      image: ghcr.io/3n-company/colorisation:main
      volumes:
        - ./photo:/imgs

  frontend:
    image: ghcr.io/3n-company/pc-frontend:master
    ports:
      - "80:3000"

volumes:
    postgres-data:
    core-data:
