name: compose

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: docker-compose up -d

      - name: Frontend alive
        run: docker run --network container:pc-frontend appropriate/curl -s --retry 30 --retry-connrefused http://localhost/

      - name: Core alive
        run: docker run --network container:pc-core appropriate/curl -s --retry 30 --retry-connrefused http://localhost:8080//photo/all-with-meta
